# Generated by Django 5.2.4 on 2026-07-27 15:47

import django.db.models.deletion
import staff.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interviewed', 'Interviewed'), ('hired', 'Hired'), ('rejected', 'Rejected')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_location', models.CharField(blank=True, max_length=255)),
                ('default_duration_hours', models.PositiveIntegerField(default=1, help_text='Default duration in hours')),
                ('required_staff_count', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for staff')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('weight_percent', models.PositiveIntegerField(default=10)),
                ('counts_against_staff', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Issue Types',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolePlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.TextField()),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('expected_outcome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_number', models.PositiveIntegerField(help_text='Duty slot: 1, 2, 3...')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('reassignment_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('reassigned_at', models.DateTimeField(blank=True, null=True)),
                ('reassigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff.event')),
                ('role', models.ForeignKey(help_text='Role for this event', on_delete=django.db.models.deletion.PROTECT, to='staff.role')),
            ],
            options={
                'verbose_name_plural': 'Assignments',
                'ordering': ['event', 'date_assigned', 'duty_number'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.eventtemplate'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('assignment', 'Assignment'), ('incident', 'Incident'), ('leave', 'Leave'), ('general', 'General')], default='general', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.assignment')),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitments', to='staff.event')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='staff.recruitment')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interviewed', 'Interviewed'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('interview_time', models.DateTimeField(blank=True, null=True)),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='staff.interviewslot')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='staff.recruitment')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantRolePlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.applicant')),
                ('role_play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.roleplay')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', staff.fields.EncryptedCharField(max_length=255)),
                ('whatsapp', staff.fields.EncryptedCharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('address', staff.fields.EncryptedTextField(max_length=355)),
                ('next_of_kin', staff.fields.EncryptedCharField(max_length=255)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', staff.fields.EncryptedCharField(max_length=255)),
                ('reliability_score', models.IntegerField(default=100, help_text='Reliability score 0-100')),
                ('reliability_notes', models.TextField(blank=True, null=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.role')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolePlayResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(help_text='What the staff member said/did')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('roleplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='staff.roleplay')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleplay_responses', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Role Play Response',
                'verbose_name_plural': 'Role Play Responses',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('attendees', models.ManyToManyField(related_name='meetings', to='staff.staff')),
            ],
            options={
                'verbose_name_plural': 'Meetings',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('unpaid', 'Unpaid Leave'), ('other', 'Other')], max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approval_notes', models.TextField(blank=True, help_text='Notes from approver', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='staff.staff')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='staff.staff'),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('interview_type', models.CharField(choices=[('written', 'Written'), ('role_play', 'Role Play')], max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='staff.applicant')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.interviewslot')),
                ('interviewers', models.ManyToManyField(related_name='interviews_conducted', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(blank=True, help_text='e.g. Late, No-Show, Uniform', max_length=100, null=True)),
                ('reliability_impact', models.CharField(blank=True, help_text='e.g. Low, Medium, High', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('reported_on', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.event')),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.issuetype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('accommodation', 'Accommodation'), ('supplies', 'Supplies'), ('meals', 'Meals'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expense_receipts/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approval_notes', models.TextField(blank=True, help_text='Optional notes for approval/rejection', null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='staff.staff')),
            ],
            options={
                'verbose_name_plural': 'Expenses',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff.staff'),
        ),
        migrations.CreateModel(
            name='StaffUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Update Log',
                'verbose_name_plural': 'Staff Update Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StaffUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_reason', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Update Request',
                'verbose_name_plural': 'Staff Update Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffUpdateApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('update_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='staff.staffupdaterequest')),
            ],
            options={
                'verbose_name': 'Staff Update Approval',
                'verbose_name_plural': 'Staff Update Approvals',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='EventTemplateRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(blank=True, default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_roles', to='staff.eventtemplate')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.role')),
            ],
            options={
                'ordering': ['role__name'],
                'unique_together': {('template', 'role')},
            },
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('event', 'duty_number', 'status'), name='unique_assignment_per_duty_status'),
        ),
    ]
