# Generated by Django 5.2.4 on 2026-07-29 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_level', models.IntegerField(choices=[(1, 'Warning'), (2, 'Critical')], default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags', to='staff.incident')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Flag',
                'verbose_name_plural': 'Flags',
                'ordering': ['-last_triggered'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2 Late incidents in 30 days', max_length=100)),
                ('rule_type', models.CharField(choices=[('date', 'Date-based'), ('issue_type', 'Issue Type Count'), ('reliability', 'Reliability Score')], max_length=20)),
                ('days', models.PositiveIntegerField(blank=True, help_text='Lookback window in days', null=True)),
                ('min_reliability_score', models.PositiveIntegerField(blank=True, help_text='For reliability rules', null=True)),
                ('threshold', models.IntegerField(default=1, help_text='Number of incidents to trigger')),
                ('action', models.CharField(help_text="e.g. 'Flag for review'", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('issue_type', models.ForeignKey(blank=True, help_text='Only for Issue Type rules', null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.issuetype')),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='ApplicationStatus',
        ),
        migrations.AddField(
            model_name='flag',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='staff.rule'),
        ),
        migrations.AlterUniqueTogether(
            name='flag',
            unique_together={('staff', 'rule')},
        ),
    ]
