# Generated by Django 5.2.4 on 2026-07-29 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_flag_rule_delete_applicationstatus_flag_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewslot',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_slots', to='staff.applicant'),
        ),
    ]
