# Generated by Django 5.2.4 on 2026-07-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_notification_action_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='annual_leave_balance',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='casual_leave_balance',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='staff',
            name='sick_leave_balance',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
