# Generated by Django 5.2.4 on 2026-08-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_event_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtemplate',
            options={'ordering': ['name'], 'verbose_name': 'Event Template', 'verbose_name_plural': 'Event Templates'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['name'], 'verbose_name': 'Staff Member', 'verbose_name_plural': 'Staff Members'},
        ),
    ]
