# Generated by Django 5.2.4 on 2026-07-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_alter_staff_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
