# Generated by Django 5.2.4 on 2026-07-12 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_assignment_end_time_assignment_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='staffupdaterequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Staff Update Request', 'verbose_name_plural': 'Staff Update Requests'},
        ),
        migrations.RemoveConstraint(
            model_name='assignment',
            name='unique_active_assignment_per_duty',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='related_event',
        ),
        migrations.RemoveField(
            model_name='staffupdaterequest',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='default_duration_hours',
            field=models.PositiveIntegerField(default=1, help_text='Default duration in hours'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='default_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for staff'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='required_staff_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitments', to='staff.event'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='title',
            field=models.CharField(default='Old Recruitment', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='staff.recruitment'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interviewed', 'Interviewed'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventtemplaterole',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], default='open', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('event', 'duty_number', 'status'), name='unique_assignment_per_duty_status'),
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='staff.recruitment'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='staff.interviewslot'),
        ),
        migrations.AddField(
            model_name='interview',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.interviewslot'),
        ),
    ]
