# Generated by Django 5.2.4 on 2026-07-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0025_interviewslot_alter_staffupdaterequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(blank=True, help_text='e.g. Late, No-Show, Uniform', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='reliability_impact',
            field=models.CharField(blank=True, help_text='e.g. Low, Medium, High', max_length=100, null=True),
        ),
    ]
