"""
Django settings for staff_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

ROOT_URLCONF = 'staff_project.urls'

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-m+1abf)q6%si-7%vl0=sgof&jt^-!@$mt_*vir3s_l%_6*_n)p')

DEBUG = False  # 1. Change to False for Render

ALLOWED_HOSTS = ['.onrender.com', 'localhost', '127.0.0.1']  # 2. .onrender.com is correct now ✅

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600,
        ssl_require=True
    )
}

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'staff.apps.StaffConfig',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 3. Add this line right here
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # for your custom templates
        'APP_DIRS': True,  # ← This is the fix for admin templates
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ... keep everything else same ...

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # 4. Add this line
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'  # 5. Add this line

FERNET_KEY = '2ATJ44SLjUK2w0HLf6lcLHLWui0YSkMH3KpALLaWb0U='

LOGIN_REDIRECT_URL = '/staff/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Create default superuser on startup if it doesn't exist
import os
from django.contrib.auth import get_user_model

if os.environ.get('RENDER'):
    User = get_user_model()
    if not User.objects.filter(username='bamboo3').exists():
        User.objects.create_superuser('bamboo3', 'admin@test.com', 'TempPass123')
        print("Superuser bamboo3 created on startup")

