from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('login/', views.bamboo_login, name='bamboo_login'),
    path('incident/add/', views.IncidentCreateView.as_view(), name='incident_add'),
    path('', views.StaffListView.as_view(), name='staff_list'),
    path('create/', views.StaffCreateView.as_view(), name='staff_create'),
    path('tasks/', views.TaskListView.as_view(), name='task_list'),
    path('<int:pk>/update/', views.StaffUpdateView.as_view(), name='staff_update'),
    path('<int:pk>/delete/', views.StaffDeleteView.as_view(), name='staff_delete'),
    path('event/', views.EventListView.as_view(), name='event_list'),
    path('event/new/', views.EventCreateView.as_view(), name='event_create'),
    path('event/<int:pk>/update/', views.EventUpdateView.as_view(), name='event_update'),
    path('event/<int:pk>/', views.EventDetailView.as_view(), name='event_detail'),
    path('event/<int:event_id>/assignments/', views.AssignmentListView.as_view(), name='assignment_list'),
    path('event/<int:event_id>/create-from-template/', views.create_assignments_from_template, name='create_from_template'),
    path('event-status/', views.event_status, name='event_status'),
    path('event/<int:event_id>/auto-fill/', views.auto_fill_roster, name='auto_fill_roster'),
    path('auto-fill-all/', views.auto_fill_all_events, name='auto_fill_all_events'),
    path('recruitment/', views.RecruitmentListView.as_view(), name='recruitment_list'),
    path('recruitment/new/', views.RecruitmentCreateView.as_view(), name='recruitment_create'),
    path('recruitment/<int:recruitment_id>/', views.RecruitmentDetailView.as_view(), name='recruitment_detail'),
    path('recruitment/<int:recruitment_id>/applicant/add/', views.ApplicantCreateView.as_view(), name='applicant_add'),
    path('recruitment/<int:recruitment_id>/apply/', views.apply_to_recruitment, name='apply_to_recruitment'),       
    path('recruitment/<int:recruitment_id>/applicants/', views.RecruitmentApplicantsView.as_view(), name='recruitment_applicants'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('role_play/', views.RolePlayListView.as_view(), name='role_play_list'),
    path('role_play/new/', views.RolePlayCreateView.as_view(), name='role_play_create'),
    path('role_play/<int:pk>/update/', views.RolePlayUpdateView.as_view(), name='role_play_update'),
    path('role_play/<int:pk>/delete/', views.RolePlayDeleteView.as_view(), name='role_play_delete'), 
    path('role_play/<int:pk>/', views.RolePlayDetailView.as_view(), name='role_play_detail'), 
    path('role_play/<int:pk>/start/', views.StartScenarioView.as_view(), name='start_scenario'), 
    path('recruitment/<int:recruitment_id>/close/', views.CloseRecruitmentView.as_view(), name='close_recruitment'), 
    path('recruitment/<int:recruitment_id>/delete/', views.RecruitmentDeleteView.as_view(), name='recruitment_delete'), 
    path('recruitment/<int:recruitment_id>/update/', views.RecruitmentUpdateView.as_view(), name='recruitment_update'),  
    path('recruitment/<int:recruitment_id>/edit/',  views.EditRecruitmentView.as_view(), name='recruitment_edit'),  
    path('recruitment/<int:recruitment_id>/export_csv/', views.ExportApplicantsCSVView.as_view(), name='export_applicants_csv'),  
    path('recruitment/<int:recruitment_id>/send_email/', views.SendEmailToApplicantsView.as_view(), name='send_email_to_applicants'), # FIXED HERE
    path('recruitment/<int:recruitment_id>/schedule_interviews/', views.ScheduleInterviewsView.as_view(), name='schedule_interviews'), 
    path('recruitment/<int:recruitment_id>/manage_interview_slots/', views.ManageInterviewSlotsView.as_view(), name='manage_interview_slots'),
    path('api/events/<int:pk>/assignments/', views.create_assignment, name='create_assignment'),
    path('api/assignments/<int:assignment_id>/update_role/', views.update_assignment_role, name='update_assignment_role'),
    path('api/assignments/<int:assignment_id>/reassign/', views.reassign_assignment, name='reassign_assignment'),
    path('api/assignments/<int:assignment_id>/replace_staff/', views.replace_staff, name='replace_staff'),
    path('profile/edit/', views.StaffProfileUpdateView.as_view(), name='staff_profile_edit'),
    path('<int:pk>/', views.StaffDetailView.as_view(), name='staff_detail'),
    path('slot/<int:slot_id>/applicants/', views.SlotApplicantsView.as_view(), name='slot_applicants'),
    path('slot/<int:slot_id>/delete/', views.DeleteSlotView.as_view(), name='delete_slot'),
    path('dashboard/export-csv/', views.ExportStaffCSVView.as_view(), name='export_staff_csv'),
    path('dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('notifications/<int:notification_id>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/mark-all-read/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('assignment/<int:pk>/accept/', views.accept_assignment, name='accept_assignment'),
    path('assignment/<int:pk>/decline/', views.decline_assignment, name='decline_assignment'),
]